### ISSUE TITLE
Problem to use tds in k8s

### ISSUE THREAD

**Issue by bepintocosta** [Unidata/tds#384]
Hello,

I'm attempting to implement the TDS in the k8s infrastructure, but cataloginit.log constantly returns this error.

![image](https://github.com/Unidata/tds/assets/59772537/a68109f9-518f-47ad-95fc-e71a3267ca27)

Do you have any configuration or anything else that can help with this issue?

Best Regards
Bruno Costa

**Comment by haileyajohnson** [comment]
I don't know anything really about configuring Kubernetes, and you haven't provided a lot of information to go on, but it appears you don't have enough (or, indeed, any) space to initialize the TDS caches.

**Comment by abkfenris** [comment]
We're using THREDDS in Kubernetes using the `[unidata/thredds-docker`](https://hub.docker.com/r/unidata/thredds-docker) images, and we haven't hit a similar issue. 

Are you providing any volumes for THREDDS to work with? Here's what one of our deployments looks like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-thredds
  name: data-thredds
spec:
  selector:
    matchLabels:
      app: data-thredds
  template:
    metadata:
      labels:
        app: data-thredds
    spec:
      containers:
        - image: 'unidata/thredds-docker:5.4'
          name: thredds
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /mnt/efs
              name: efs
            - mountPath: /usr/local/tomcat/content/thredds/
              name: efs
              subPath: services/thredds/
      volumes:
        - name: efs
          persistentVolumeClaim:
            claimName: efs
```

We're mapping both the full `efs` volume in at `/mnt/efs`, but also a specific path within it to `/usr/local/tomcat/content/thredds/`.

**Comment by lesserwhirls** [comment]
Also, keep in mind that each instance of the TDS will need its own configuration directory, as certain things cannot be shared between instances (such as the caches under `/usr/local/tomcat/content/thredds/cache`). You could probably get away with sharing the configuration catalogs and thymeleaf templates, but for sure not the cache directory.

**Comment by bepintocosta** [comment]
> ```yaml
> thredds
> ```

And in your configuration? 

You appoint the tds content folder to the the mount /mnt/efs?

Look to my k8s manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: thredds
  name: thredds-qa
  labels:
    app: thredds-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thredds-qa
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thredds-qa
    spec:
      containers:
        - name: thredds
          image: unidata/thredds-docker:5.5-SNAPSHOT
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: thredds-config
                optional: false
          resources:
              limits:
                cpu: 400m
                memory: 5Gi
              requests:
                cpu: 400m
                memory: 5Gi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: tomcat-users
              mountPath: "/usr/local/tomcat/conf/tomcat-users.xml" 
              subPath: tomcat-users.xml
            - name: thredds-content
              mountPath: /mnt/efs
            - name: thredds-content
              mountPath: "/usr/local/tomcat/content/thredds"
              subPath: services/thredds/
            - name: thredds-s3
              mountPath: "/usr/local/tomcat/.aws"
      volumes:
         - name: tomcat-users
           configMap:
            name: tomcat-users
         - name: thredds-s3
           secret:
              secretName: s3-secrets
              optional: true
         - name: thredds-content
           persistentVolumeClaim:
             claimName: thredds-content-qa
 ````
